### ISSUE TITLE
ontario page

### ISSUE THREAD

**Issue by dr-mvb** [Smittyvb/roadsides#25]
- lots of thumbnails not loading - just loading very slowly? or some other problem?
- oil can in niagara-on-the-lake still has the "NEW" graphic - remove that graphic! (is it still anywhere else on the site?)

**Comment by dr-mvb** [comment]
- I removed the "NEW" .gif -- Smitty: please search all files to see if "new.gif" is used anywhere else on the site

**Comment by dr-mvb** [comment]
Smitty: the reason that the thumbnails are not loading is because all of those .jpg files are gone!!!!

- what happened?
- we need them back!!!

**Comment by dr-mvb** [comment]
Smitty: I have noticed something else. The problems start on the Ontario page near the Shoe Tree in Minden. Starting at that point on the page, all of the links that are associated with the thumbnails are to the .htm pages, NOT .html pages. All the thumbnails above the problem are correctly pointing to .html pages. Unless this is just a weird coincidence, it must be related to the problem of the missing .jpg files. But how???

Crazy!

**Comment by Smittyvb** [comment]
I changed all the links from xxx1.jpg to xxx.jpg.
