### ISSUE TITLE
ERS

### ISSUE THREAD

**Issue by dr-mvb** [Smittyvb/roadsides#28]
- update "ERS" credits on photos to read "Ed Solonyka"

**Comment by Smittyvb** [comment]
Why is ERS Ed?

**Comment by dr-mvb** [comment]
He used his initials instead of his full name: Edward Richard Solonyka.

**Comment by dr-mvb** [comment]
found another "ERS" -- http://roadsideattractions.ca/goose.html

**Comment by dr-mvb** [comment]
found and fixed another dozen-ish ERS references
