### ISSUE TITLE
Remove Bravenet Scripts

### ISSUE THREAD

**Issue by Smittyvb** [Smittyvb/roadsides#3]
Remove the various scripts that mention "bravenet"

**Comment by dr-mvb** [comment]
Why is this issue #3? Why is no issues #1 and #2?

**Comment by Smittyvb** [comment]
They were for pull requests.

**Comment by dr-mvb** [comment]
should we be using these issues instead of our to-do list?

**Comment by Smittyvb** [comment]
yep.

**Comment by Smittyvb** [comment]
turned out index.html was the only file with bravenet
