### ISSUE TITLE
inukshuk

### ISSUE THREAD

**Issue by dr-mvb** [Smittyvb/roadsides#30]
kinukshuk.html
- was shown as being in kingston, really is in Seeley's Bay
- need to:

- [x] update page

- [x] update name and move to correct spot in alphabetical list

- [x] update name and move to correct spot in types list

- [x] change location from kingston to seeley's bay in spreadsheet

- [ ] update name and move to correct spot in ontario list (alphabetical by 'seeley's bay')

**Comment by dr-mvb** [comment]
Smitty: I have doe everything on the list EXCEPT that on the Ontario page, this Inukshuk now say's it is in Seeley's Bay, but it is still alphatbetically where Kingston belongs, because if I move it I will probably mess up the formatting of the table -- please move it so it is after "Railroad Jigger - Schreiber"

**Comment by dr-mvb** [comment]
ALSO:  need to either move it in Google Maps (if it already is on Google Maps, or else add it to Google Maps. 

Smitty: show me how to do this.

**Comment by dr-mvb** [comment]
note: you will want to do this at the same time as issue 32, because they both involve changing the order of roadsides on the ontario page

**Comment by Smittyvb** [comment]
This IS in the right place?

**Comment by dr-mvb** [comment]
yup
