### ISSUE TITLE
Contact Us - Blog

### ISSUE THREAD

**Issue by Smittyvb** [Smittyvb/roadsides#7]
Add a "Contact Us" button to blog.

**Comment by dr-mvb** [comment]
clarify -- add "Contact us" as a link on the side menu

**Comment by Smittyvb** [comment]
Should it just be an email link?

**Comment by dr-mvb** [comment]
Yes

**Comment by dr-mvb** [comment]
Update: make this link land on a page with a list of contact info, etc. See my handwritten notes for this page.

**Comment by dr-mvb** [comment]
done
